language: cpp
dist: bionic
jobs:
  include:
    # linus
    - name: "ast2600, linus"
      env: MACHINE=ast2600 CONFIG=aspeed_g5_defconfig
    - name: "ast2500, linus"
      env: MACHINE=ast2500 CONFIG=aspeed_g5_defconfig
    - name: "ast2400, linus"
      env: MACHINE=ast2400 CONFIG=aspeed_g4_defconfig
    - name: "multi v7 on ast2600, linus"
      env: MACHINE=ast2600 CONFIG=multi_v7_defconfig
    - name: "multi v5 on ast2400, linus"
      env: MACHINE=ast2400 CONFIG=multi_v5_defconfig

    # openbmc dev-5.8
    - name: "ast2600, openbmc 5.8"
      env: MACHINE=ast2600 CONFIG=aspeed_g5_defconfig REPO=dev-5.8
    - name: "ast2500, openbmc 5.8"
      env: MACHINE=ast2500 CONFIG=aspeed_g5_defconfig REPO=dev-5.8
      if: type = cron
    - name: "ast2400, openbmc 5.8"
      env: MACHINE=ast2400 CONFIG=aspeed_g4_defconfig REPO=dev-5.8
      if: type = cron

    # openbmc dev-5.4
    - name: "ast2600, openbmc 5.4"
      env: MACHINE=ast2600 CONFIG=aspeed_g5_defconfig REPO=dev-5.4
    - name: "ast2500, openbmc 5.4"
      env: MACHINE=ast2500 CONFIG=aspeed_g5_defconfig REPO=dev-5.4
      if: type = cron
    - name: "ast2400, openbmc 5.4"
      env: MACHINE=ast2400 CONFIG=aspeed_g4_defconfig REPO=dev-5.4
      if: type = cron

    # linux-next
    - name: "ast2600, linux-next"
      env: MACHINE=ast2600 CONFIG=aspeed_g5_defconfig REPO=linux-next
    - name: "ast2500, linux-next"
      env: MACHINE=ast2500 CONFIG=aspeed_g5_defconfig REPO=linux-next
      if: type = cron
    - name: "ast2400, linux-next"
      env: MACHINE=ast2400 CONFIG=aspeed_g4_defconfig REPO=linux-next
      if: type = cron
    - name: "multi v7 on ast2600, linux-next"
      env: MACHINE=ast2600 CONFIG=multi_v7_defconfig REPO=linux-next
      if: type = cron
    - name: "multi v5 on ast2400, linux-next"
      env: MACHINE=ast2400 CONFIG=multi_v5_defconfig REPO=linux-next
      if: type = cron
compiler: gcc
os: linux
cache:
  directories:
    - .ccache
services:
  - docker
script:
  - |
    docker run \
        --env ARCH=${ARCH} \
        --env LD=${LD} \
        --env LLVM_IAS=${LLVM_IAS} \
        --env REPO=${REPO} \
        --env BOOT=${BOOT} \
        --env MACHINE=${MACHINE} \
        --env CONFIG=${CONFIG} \
        --rm \
        --workdir /travis \
        --volume ${TRAVIS_BUILD_DIR}:/travis \
        shenki/kernel-build:llvm${LLVM_VERSION:-12}-latest /bin/bash -c './env-setup.sh && ./driver.sh && ccache -s'
after_script:
  - sleep 1
notifications:
  email:
    recipients:
      - joel@jms.id.au
    on_success: never
    on_failure: always
    if: type = cron
