language: cpp
matrix:
  include:
    - name: "ARCH=ppc32"
      env: ARCH=ppc32
    - name: "ARCH=ppc64le"
      env: ARCH=ppc64le
    - name: "ARCH=ppc64"
      env: ARCH=ppc64
    - name: "ARCH=ppc32  REPO=linux-next"
      env: ARCH=ppc32 REPO=linux-next
    - name: "ARCH=ppc64"
      env: ARCH=ppc64
    - name: "ARCH=ppc64le  REPO=linux-next"
      env: ARCH=ppc64le REPO=linux-next
compiler: gcc
os: linux
dist: trusty
sudo: required
cache:
  directories:
    - .ccache
services:
  - docker
script:
  - |
    docker run \
        --env ARCH=${ARCH} \
        --env LD=${LD} \
        --env REPO=${REPO} \
        --rm \
        --workdir /travis \
        --volume ${TRAVIS_BUILD_DIR}:/travis \
        clangbuiltlinux/ubuntu /bin/bash -c './env-setup.sh && ./driver.sh && ccache -s'
after_script:
  - sleep 1
notifications:
  email:
    receipients:
      - ndesaulniers@google.com
      - natechancellor@gmail.com
    on_success: never
    on_failure: always
