language: cpp
jobs:
  include:
compiler: gcc
os: linux
cache:
  directories:
    - .ccache
services:
  - docker
script:
  - |
    docker run \
        --env ARCH=${ARCH} \
        --env LD=${LD} \
        --env LLVM_IAS=${LLVM_IAS} \
        --env REPO=${REPO} \
        --env BOOT=${BOOT} \
        --rm \
        --workdir /travis \
        --volume ${TRAVIS_BUILD_DIR}:/travis \
        clangbuiltlinux/ubuntu:llvm${LLVM_VERSION:-12}-latest /bin/bash -c './env-setup.sh && ./driver.sh && ccache -s'
after_script:
  - sleep 1
notifications:
  email:
    recipients:
      - ndesaulniers@google.com
      - natechancellor@gmail.com
    on_success: never
    on_failure: always
    if: type = cron
