language: cpp
matrix:
  include:
    # linux
    - name: "ARCH=arm"
      env: ARCH=arm
    - name: "ARCH=arm64 LD=ld.lld"
      env: ARCH=arm64 LD=ld.lld-8
    - name: "ARCH=ppc64le"
      env: ARCH=ppc64le
    - name: "ARCH=x86_64"
      env: ARCH=x86_64
    # linux (cron only)
    - name: "ARCH=arm64"
      env: ARCH=arm64
      if: type = cron
    # linux-next (cron only)
    - name: "ARCH=arm REPO=linux-next"
      env: ARCH=arm REPO=linux-next
      if: type = cron
    - name: "ARCH=arm64 REPO=linux-next"
      env: ARCH=arm64 REPO=linux-next
      if: type = cron
    - name: "ARCH=arm64 LD=ld.lld REPO=linux-next"
      env: ARCH=arm64 LD=ld.lld-8 REPO=linux-next
      if: type = cron
    - name: "ARCH=ppc64le  REPO=linux-next"
      env: ARCH=ppc64le REPO=linux-next
      if: type = cron
    - name: "ARCH=x86_64 REPO=linux-next"
      env: ARCH=x86_64 REPO=linux-next
      if: type = cron
compiler: gcc
os: linux
dist: trusty
sudo: required
cache:
  directories:
    - .ccache
services:
  - docker
script:
  - docker create -v ${TRAVIS_BUILD_DIR}:/travis --name travis debian:sid
  - docker run --env ARCH=${ARCH} --env LD=${LD} --rm --volumes-from travis debian:sid /bin/bash -c 'cd /travis && ./debian-setup.sh && ./driver.sh && ccache -s'
after_script:
  - sleep 1
